<?php

/**
 * @copyright  2015 (c) Stanimir Dimitrov.
 * @license    http://www.opensource.org/licenses/mit-license.php  MIT License
 *
 * @version    0.0.23
 *
 * @link       https://github.com/Stanimirdim92/unnamed
 */

if ($this->viewModel()->getCurrent()->getChildren() != null) {
    $view = $this->viewModel()->getCurrent()->getChildren()[0];
?>
<!doctype html>
<html itemscope itemtype="http://schema.org/WebPage" prefix="og: http://ogp.me/ns#" lang="<?=$this->layout()->lang?>">
    <head>
        <meta charset="utf-8">
        <title><?=$this->escapeHtml($this->headTitle()->renderTitle());?></title>
<?php
            echo $this->headMeta();
            echo $this->placeholder('customHead');
            echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath().'/favicon.ico']);
?>
        <meta property="og:site_name" content="<?=$this->escapeHtml($this->headTitle()->renderTitle());?>">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/apple-touch-icon.png');?>">
        <meta name="msapplication-config" content="<?=$this->basePath('/browserconfig.xml');?>" />
        <link rel="canonical" href="<?=$this->serverUrl(true);?>">
        <link rel="shortlink" href="<?=$this->serverUrl(true);?>">
    </head>
    <body>
        <div id="content-wrapper">
            <!-- Header, banner, navigation menu -->
            <header id="header">
                <nav id="nav" class="clearfix" aria-label="main navigation">
                    <?=$view->menu;?>
                </nav>
            </header>

            <aside class="aside" id="aside-menu-left">

            </aside>

            <main id="main">
<?php

                if ($this->layout()->flashMessages) {
                    foreach ($this->layout()->flashMessages as $msg) {
                        foreach ($msg as $context => $message) {
                            echo "<div class='".$context."'>
                                    <ul>
                                        <li role='alert'>
                                            <i class='fa-fw fa fa-".$context."'></i>".$message."
                                            <button role='button' aria-pressed='false' aria-label='".$this->translate("DELETE")."' type='button' class='btn btn-default close close'><i class='fa fa-times'></i></button>
                                        </li>
                                    </ul>
                                  </div>
                            ";
                        }
                    }
                    $this->layout()->flashMessages = null;
                }

                /**
                 * Every other html element must come from content variable
                 * or in other simple words: Do not put any other html element around this code!
                 */
                echo $this->layout()->content;
?>
            </main>

            <aside class="aside" id="aside-menu-right">

            </aside>
        </div>

        <footer class="c" id="footer">
            <small>Copyright <time datetime="2015 - <?=date("Y");?>">2015 - <?=date("Y");?></time> &copy; Stanimir Dimitrov. </small>
        </footer>
    </body>
</html>
<?php
}
