engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Design/LongMethod:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.php"
exclude_paths:
  - config/**/*
  - data/**/*
  - public/assets/**/*
  - public/layouts/**/*
  - gulpfile.js
  - test/**/*
  - test/*
  - .editorconfig
  - .codeclimate.yml
  - LICENSE.md
  - README.md
  - package.json
  - .*.json
  - .*.yml
  - .*rc
