preset: recommended

linting: true

enabled:
  - align_double_arrow

disabled:
  - unalign_double_arrow

finder:
  name:
    - "*.php"
  path:
    - "module"
    - "data"
    - "config"
    - "public"
