language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

install:
  - sudo apt-get install parallel
  - sudo apt-get install nodejs npm
  - /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/composer self-update
  - travis_retry composer install --optimize-autoloader

before_script:
  - mkdir -p build/coverage
  - mkdir -p build/coverage
  - mkdir -p data/logs
  - chmod -R 777 data/logs
  - mysql -e 'create database IF NOT EXISTS xj;' -uroot
  - pip install --user codecov
  - cp config/autoload/doctrine.local.php.dist config/autoload/doctrine.local.php
  - php -S localhost:8000 -t public/ &
  - sleep 1

script:
  - ls -d module/*/test/PHPUnit | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c {}/phpunit.xml;' || exit 1
  - cd ..

after_success:
  - codecov

after_script:
  - php coverage-report.php
  - php vendor/bin/coveralls -v --exclude-no-stmt

notifications:
  email: true

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm
