<?php
if(!empty($this->news)) {
   /**
    * @var $new Admin\Model\Content
    */
    foreach($this->news as $new) {
        $dateTime = date("Y-m-d", strtotime($new->getDate()));
        $dateTimeShow = date("M d, Y", strtotime($new->getDate()));
?>
            <article role="article" class="post-content" itemscope itemprop="event" itemtype="http://schema.org/Article">
<?php
                if ($new->getPreview() != null) {
?>
                    <figure itemscope itemtype="http://schema.org/ImageObject" class="image-size">
                        <a itemprop="url" href="/userfiles/preview/<?=$new->getPreview();?>" id="news_image" title="<?=$new->getTitle();?>">
                            <img itemprop="image" src="/userfiles/preview/<?=$new->getPreview();?>" title="<?=$new->getTitle()?>" alt="<?=$new->getTitle();?>" />
                        </a>
                    </figure>
<?php
                }
?>
                <h2 role="heading" itemscope itemprop="name" class="post-title"><?=$new->getTitle();?></h2>

                <time datetime="<?=$dateTime?>" class="post-date">
                    <?=$this->translate("POSTED_ON");?>&nbsp;<meta itemprop="datePublished" content="<?=$dateTime?>"><?=$dateTimeShow?>
                </time>

                <p itemscope itemprop="text" class="post-text"><?=substr(strip_tags($new->getText()), 0, 300)."...";?></p>
                <br>
<?php
                if (mb_strlen($new->getText()) > 0) {
?>
                    <p class="read-more">
                        <a hreflang='<?=$this->layout()->lang?>' itemscope itemprop="url" title="<?=$this->translate("READ_MORE")?>" class="read-more-link" href="<?=$this->url('application/default', ['controller' => 'news', 'action' => 'post', 'post' => $new->getTitleLink()]);?>"><?=$this->translate("READ_MORE")?></a>
                    </p>
<?php
                }
?>
            </article>
<?php
    }
    echo $this->paginationControl($this->news, 'Sliding', 'application/pagination', ['route' => 'application/default']);
} else {
    echo "<h3 itemscope itemprop='name' class='c no-content'>".$this->translate("NO_CONTENT")."</h3>";
}
