<section>
    <div class="table-style">
        <ul class="table-header">
            <li class="table-cell "><?=$this->translate("TITLE")?></li>
            <li class="table-cell "><?=$this->translate("SLUG")?></li>
            <li class="table-cell flex-b"><?=$this->translate("EDIT")?></li>
            <li class="table-cell flex-b"><?=$this->translate("DELETE")?></li>
        </ul>
<?php
        /**
         * @var $category array
         */
        foreach($this->paginator as $category) {
?>
        <ul class="table-row">
            <li class="table-cell ">
                <?=$category->getTitle()?>
            </li>
            <li class="table-cell ">
                <?=$category->getSlug()?>
            </li>
            <li class="table-cell flex-b">
                <a title='<?=$this->translate("EDIT")?>' href='<?=$this->url("admin/default", ['controller' => "category", "action" => "edit", "id" => $category->getId()])?>' class='btn btn-sm orange'><i class='fa fa-pencil'></i></a>
            </li>
            <li class="table-cell flex-b">
                <button role="button" aria-pressed="false" aria-label="<?=$this->translate("DELETE")?>" type="button" title='<?=$this->translate("DELETE")?>' id='<?=$category->getId()?>' class='btn btn-sm delete dialog_delete'><i class='fa fa-trash-o'></i></button>
                <div role="alertdialog" aria-labelledby="dialog<?=$category->getId()?>Title" class='delete_<?=$category->getId()?> dialog_hide'>
                    <p id="dialog<?=$category->getId()?>Title"><?=$this->translate("DELETE_CONFIRM_TEXT")?> &laquo;<?=$category->getTitle()?>&raquo;</p>
                    <ul>
                        <li>
                            <a class='btn delete' href='<?=$this->url("admin/default", ['controller' => "category", "action" => "delete", "id" => $category->getId()])?>'><i class='fa fa-trash-o'></i> <?=$this->translate("DELETE")?></a>
                        </li>
                        <li>
                            <button role="button" aria-pressed="false" aria-label="<?=$this->translate("CANCEL")?>" type="button" title='<?=$this->translate("CANCEL")?>' class='btn btn-default cancel'><i class='fa fa-times'></i> <?=$this->translate("CANCEL")?></button>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
<?php
        }
?>
    </div>
</section>
