<div class="showRegister" id="showForm">
    <p itemprop='name' class="legend"><?=$this->translate("CREATE_ACCOUNT");?></p>
    <?php
        if (!$this->form instanceof Application\Form\RegistrationForm) {
            echo "<p itemscope itemprop='text' class='c'>{$this->form}</p>";
        } else {
           /**
            * @var $form Application\Form\RegistrationForm|string
            */
            $form = $this->form;
            $form->setAttribute('action', '/registration/processregistration');
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
        }

    ?>
</div>
