<div class="showLogin" id="showForm">
    <p itemprop='name' class="legend"><?=$this->translate("RESET_PW");?></p>
    <?php
       /**
        * @var $form \Application\Form\ResetPasswordForm
        */
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
    ?>
</div>
