<form action="/admin/content/upload" method="post" id="ajaxform" enctype="multipart/form-data" role="form">
    <div id="modal-imgupload">
        <div class="modal-window">
            <button type="button" class="blue modal-toggle modal-close fa fa-times"></button>
            <div class="modal-content">
                <div class="menu-frame">
                    <div class="buttons-frame">
                        <div class="media-router">
                            <button type="button" class="upload button"><?=$this->translate("FILE_UPLOAD")?></button>
                            <button type="button" class="gallery button"><?=$this->translate("GALLERY")?></button>
                        </div>
                    </div>
                    <div class="content-window">
                        <div class="uploader-inline">
                            <label for="imgajax" class="file-upload-label">
                                <?=$this->translate("UPLOAD_FILES")?>
                                <?php
                                    echo $this->formFile($form->get("imageUpload"));
                                ?>
                            </label>
                        </div>
                        <div class="gallery-view">
                            <div class="ajax-loader"></div>
                            <div class="view-large-image">
                                <img src="assets/prod/front/img/default.png" class="large-image">
                            </div>
                            <div class="image-grid">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
