<?php
    /**
    * @var $admin-menu \SD\Admin\Entity\AdminMenu
    */
    $adminmenu = $this->adminmenu;
?>
<section>
    <p>
        <a href="<?=$this->url("admin/default", ['controller' => "admin-menu"])?>" class="btn btn-default">
            <i class="fa fa-chevron-left"></i> <?=$this->translate("BACK")?>
        </a>
    </p>
    <div class='table-style'>
        <ul class="table-row">
            <li class="table-cell"><?=$this->translate("CAPTION")?></li>
            <li class="table-cell"><?=$adminmenu->getCaption()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->translate("MENU_ORDER")?></li>
            <li class="table-cell"><?=$adminmenu->getMenuOrder()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->translate("CONTROLLER")?></li>
            <li class="table-cell"><?=$adminmenu->getController()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->translate("ACTION")?></li>
            <li class="table-cell"><?=$adminmenu->getAction()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->translate("CLASS")?></li>
            <li class="table-cell"><i class="fa <?=$admin-menu->getClass()?>"> &dash; <?=$adminmenu->getClass()?></i></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->translate("DESCRIPTION")?></li>
            <li class="table-cell"><?=$adminmenu->getDescription()?></li>
        </ul>

<?php
        if($adminmenu->getParent()) {
?>
        <ul class="table-row">
            <li class="table-cell"><?=$this->translate("PARENT")?></li>
            <li class="table-cell">
                <a class='btn btn-default blue' href='<?=$this->url("admin/default", ['controller' => "admin-menu", "action" => "detail", "id" => $adminmenu->getParent()])?>'><i class='fa fa-info'></i></a>
            </li>
        </ul>
<?php
        }
?>
    </div>
</section>
