<div>
    <p>
        <a href="<?=$this->url("admin/default", ["controller" => "admin-menu"])?>" class="btn btn-default">
            <i class="fa fa-chevron-left"></i> <?=$this->translate("BACK")?>
        </a>
    </p>
    <div class='form-inputs'>
        <?php
            /**
             * @var \SD\Admin\Form\AdminMenuForm $form
             */
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/default', ['controller' =>'admin-menu', 'action' => 'edit', 'id'=> $this->adminMenu->getId()]));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
        ?>
    </div>
</div>
