<div>
    <p itemprop='name' class="legend"><?=$this->translate("SETTINGS");?></p>
    <?php
       /**
        * @var $form SD\Application\Form\SettingsForm
        */
        $form = $this->form;
        $form->setAttribute('action', '/settings');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();

    ?>
</div>
