<?php

/**
 * @copyright  2015 (c) Stanimir Dimitrov.
 * @license    http://www.opensource.org/licenses/mit-license.php  MIT License
 *
 * @version    0.0.23
 *
 * @link       https://github.com/Stanimirdim92/unnamed
 */

if ($this->viewModel()->getCurrent()->getChildren() != null) {
    $view = $this->viewModel()->getCurrent()->getChildren()[0];
?>
<!doctype html>
<html lang="<?=$this->layout()->lang?>">
    <head>
        <meta charset="utf-8">
        <title><?=$this->escapeHtml($this->headTitle()->renderTitle());?></title>
<?php
            echo $this->headMeta()
                ->appendName('robots', 'noindex, nofollow')
                ->appendName('author', 'Stanimir Dimitrov - stanimirdim92@gmail.com')
                ->appendName('apple-mobile-web-app-status-bar-style', 'black-translucent')
                ->appendName('HandheldFriendly', 'True')
                ->appendName('MobileOptimized', '320')
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendName('apple-mobile-web-app-capable', 'yes')
                ->appendName('mobile-web-app-capable', 'yes')
                ->appendName('apple-mobile-web-app-status-bar-style', 'black-translucent')
                ->appendHttpEquiv('cleartype', 'on')
                ->appendHttpEquiv('x-dns-prefetch-control', 'on');

            echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath().'/favicon.ico'])
                ->prependStylesheet($this->basePath('/layouts/default/back/css/back.min.css'), 'screen');

?>
    </head>
    <body>
        <div id="content-wrapper">
            <!-- Header, banner, navigation menu -->
            <header id="header">
                <nav id="nav" aria-label="main navigation">
                    <ul>
                        <?=$view->menuAdmin;?>
                    </ul>
                </nav>
            </header>

            <aside class="aside" id="aside-menu-left">

            </aside>

            <main id="main">
                <!-- Breadcrumbs -->
                <div class="breadcrumbs">
                    <ul>
                    <li><a hreflang='<?=$this->layout()->lang?>' href="/admin"><?=$this->translate("DASHBOARD");?></a> &sol;</li>
<?php
                    if (!empty($view->breadcrumbs)) {
                        foreach($view->breadcrumbs as $bread) {
                                echo "<li><a hreflang='{$this->layout()->lang}' href='{$bread["reference"]}'>{$bread["name"]}</a></li> &sol;";
                        }
                    }
                echo "</ul>";
            echo "</div>";

                /**
                 * All messages passed from $this->getLayoutMessages() plugin method are showed with this code
                 */
                if ($this->layout()->flashMessages) {
                    foreach ($this->layout()->flashMessages->getCurrentMessages() as $context => $message) {
                        echo "<div class='".$this->layout()->flashMessages->getNamespace()."'>
                                <ul>
                                    <li role='alert'>
                                        <i class='fa-fw fa fa-".$this->layout()->flashMessages->getNamespace()."'></i>{$message}
                                        <button role='button' aria-pressed='false' aria-label='".$this->translate("DELETE")."' type='button' class='btn btn-default close close'><i class='fa fa-times'></i></button>
                                    </li>
                                </ul>
                              </div>
                        ";
                    }
                }

                /**
                 * Every other html element must come from content variable
                 * or in other simple words: Do not put any other html element around this code!
                 */
                echo $this->layout()->content;
?>
            </main>

            <aside class="aside" id="aside-menu-left">

            </aside>

            <footer class="c" id="footer">
                <small>Copyright <time datetime="2015 - <?=date("Y");?>">2015 - <?=date("Y");?></time> &copy; dzfsdsfg Dimitrov. </small>
            </footer>
        </div>
<?php
        echo $this->headScript()
            ->prependFile($this->basePath('layouts/default/back/js/back.min.js'))
?>
    </body>
</html>
<?php
}
