<?php

// Generated by ZF2's ./bin/templatemap_generator.php
return [
    'application/contact/index' => __DIR__.'/view/application/contact/index.phtml',
    'application/index/index' => __DIR__.'/view/application/index/index.phtml',
    'application/login/index' => __DIR__.'/view/application/login/index.phtml',
    'application/login/newpassword' => __DIR__.'/view/application/login/newpassword.phtml',
    'application/login/resetpassword' => __DIR__.'/view/application/login/resetpassword.phtml',
    'application/menu/post' => __DIR__.'/view/application/menu/post.phtml',
    'application/news/index' => __DIR__.'/view/application/news/index.phtml',
    'application/news/post' => __DIR__.'/view/application/news/post.phtml',
    'application/pagination' => __DIR__.'/view/application/pagination.phtml',
    'application/registration/index' => __DIR__.'/view/application/registration/index.phtml',
    'error/index' => __DIR__.'/view/error/index.phtml',
    'layout/layout' => __DIR__.'/view/layout/layout.phtml',
];
