<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return [
    'themes/index/index'         => __DIR__ . '/view/themes/index/index.phtml',
    'error/index'                     => __DIR__ . '/view/error/index.phtml',
    'layout/layout'                   => __DIR__ . '/view/layout/layout.phtml',
];
